- update.mjs
Added the following to `update.mjs` :
- turbo.json
- .nvmrc
> (chore): added nvmrc and turborepo

- update.mjs
Added the following to `update.mjs` :
- vetur.config.*
- .sentryclirc
> (chore): added vetur and sentry

- update.mjs
> chore: add releaserc and gitlab config

- update.mjs
source: [conventional-changelog](https://github.com/conventional-changelog/commitlint#config)
> feat: add .commitlintrc* config file

- README.md
- update.mjs
**Some explanations**
readme*.md: [add i18n readme*.md, for example: readme.zh_CN.md](https://github.com/antfu/vscode-file-nesting-config/commit/3555b76aaa58b3d1d67c090979124e1c45cbbd98)
.air*: air is to go what nodemon is to node
> add readme*.md nodemon.* pm2.* file

- update.mjs
https://dprint.dev/  - dprint
> A pluggable and configurable code formatting platform written in [Rust](https://www.rust-lang.org/).
> Added support for dprint

- README.md
Can be very handy to handle file structures that includes component storybook stories or typescript declaration in the same folder of a vue component.
> Add files related to vue components

- update.mjs
- ✨ composer & locks
- 🔧 add for phpunit.xml & phpunit.xml.dist
- 🔧 add for psalm(lint)
> add php composer

- .github/workflows/lint.yml
- package.json
- update.mjs
Find some eslint format errors in code, need be fix
> chore: add lint workflow

- update.mjs
- .phpunit.result.cache
- .php-cs-fixer.cache
> Add php related cache files under composer

- update.mjs
- .NET project related files
- .NET related files
.NET Core project
ASP.NET WebForm (C#)
ASP.NET WebForm (VB)
> Add .NET project files

- update.mjs
Add `docker-compose.yml` to Docker group
> Docker Compose

- update.mjs
Group Gatsby configuration files
> feat: Gatsby

- update.mjs
Hi, thank you for this amazing config! I just added some groups for Elixir and [Phoenix LiveView](https://www.phoenixframework.org/) projects.
> Add configs for Elixir and Phoenix LiveView

- update.mjs
a Typical nestjs module consists of 
- module
- controller/resolver
- service
> Add support for nestjs module files

- extension/src/fetch.ts
> fix(settings): respect existing value for "fileNesting.expand" if present

- update.mjs
Add [commitizen](https://github.com/commitizen/cz-cli) `.czrc` & [standard-version](https://github.com/conventional-changelog/standard-version) `.versionrc`, `.versionrc.json`, and `.versionrc.js` config files.
> feat: add commitizen and standard-version config files

- extension/README.md
- extension/package.json
- extension/src/constants.ts
- extension/src/fetch.ts
> feat(extension): make the url configurable

- extension/package.json
> chore: use onStartupFinished

- update.mjs
Angular components usually consist of the main component file, along with separate files for the HTML template, CSS file and test specification.
By convention, the main component file has the extension `.component.ts`, such as `my-awesome-thing.component.ts` and the other files use the same prefix (including component):
- .component.html: HTML template
- .component.spec.ts: test specification
- .component.css, .component.scss, .component.sass, .component.less: CSS file (depending on the chosen CSS preprocessor)
> feat: add Angular components config

- update.mjs
Adds unlighthouse config to `services` list
> add unlighthouse

- update.mjs
Added file nesting for histoire config file and its *.story.vue files
- None
> Added Histoire Config

- update.mjs
Added file nesting for [contentlayer config file](https://www.contentlayer.dev).
> Added Contentlayer config

- update.mjs
> add pubspec_overrides.yaml to pubspecYAML for dart

- README.md
> feat: support mts

- update.mjs
Adds support to collapse `npm-shrinkwrap.json` under `package.json`
N/A
`npm-shrinkwrap.json` is generated with the `npm shrinkwrap` command and is used when publishing packages.
> feat: add npm-shrinkwrap.json

- update.mjs
UnoCSS accepts both `unocss.config` and `uno.config` for configuring UnoCSS.
N/A.
> feat: add missing unocss config file

- update.mjs
https://eslint.org/docs/latest/use/configure/configuration-files-new
> feat: add ESLint flat config file

- update.mjs
Add files used by https://houdinigraphql.com/ in SvelteKit.
> feat: add Houdini files in SvelteKit

- update.mjs
Add config files for [semantic-release](https://github.com/semantic-release/semantic-release)
> feat: add semantic-release config files

- update.mjs
Add [electron-builder](https://www.electron.build/) config file to group build tools.
None.
None.
> feat: add electron-builder

- update.mjs
Added release please config files
> fix: add support for release-please

- update.mjs
Adds entries for `i18n.config.*` & `vuetify.config.*` to be listed under frameworks config files (`nuxt.config` in my case).
N/A
N/A
> feat: add i18n.config & vuetify.config

- update.mjs
Add `bun install` generated lockfile `bun.lockb` to workspaces
null
- https://bun.sh/docs/install/lockfile
> feat: bun.lockb to workspaces

- update.mjs
> feat: add scss for tsx

- update.mjs
> feat: add CMakeCache.txt

- update.mjs
the avalonia cross-platform ui uses similar naming structure to the existing .xaml catch but just with .axaml instead
> feat: add avalonia .axaml

- update.mjs
https://github.com/webpro/knip#default-configuration 
Not sure where to place it so I created a new category `dependencyAnalysis` based on https://bestofjs.org/projects/knip
> feat: Add knip

- update.mjs
Add `sonar-project.properties` to services.
https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/scanners/sonarscanner/#configuring-your-project
> feat: Add `sonar-project.properties` to services.

- update.mjs
Add `compose.*`  under docker
https://docs.docker.com/compose/compose-file/03-compose-file/
> feat: add compose to docker

- .gitignore
- update.mjs
Fixed syntax error which causes lint script to fail
No issue linked
> chore: lint

- update.mjs
Add `ruff.toml` and `.ruff.toml` under pyprojecttoml
https://docs.astral.sh/ruff/configuration/
> feat: add ruff to pyprojecttoml

- update.mjs
Include 'poetry.toml' into pyproject nested group
> feat: include poetry.toml into pyproject group

- update.mjs
Adds `RELEASE_NOTES*` under `readme`.
> feat: add release notes to readme

- update.mjs
> feat: add `*.db` rule for SQLite databases

- update.mjs
This PR adds support for nesting python interface files with their module implementation.
https://wingware.com/doc/edit/analysis-helping-pyi-files
> feat: add support for Python interface files

- update.mjs
Biome [also supports jsonc files as configuration files](https://biomejs.dev/guides/getting-started/#configuration).
> fix: update biome.json to biome.json*

- update.mjs
Support for Winglang https://www.winglang.io/ and folding of test files underneath source file.
Been using the extension for a few months and Wing for a month or so, and this would alleviate the pain that file nesting is already solving.
> feat: support for Winglang

- update.mjs
> feat: add scss for jsx

- update.mjs
Add README_* for README file in different languages
> feat: add README_*

- update.mjs
[Bun configuration file](https://bun.sh/docs/runtime/bunfig)
> feat: add bunfig.toml

- update.mjs
> feat: support css.ts for TSX component

- update.mjs
eg: https://github.com/Dokploy/dokploy/blob/canary/README-de.md
> fix: update readme match

- update.mjs
Put sanity configuration files under `sanity.config.*`
- `sanity.config.*`: sanity configuration file https://www.sanity.io/docs/configuration
- `sanity.cli.*`: sanity cli configuration file https://www.sanity.io/docs/cli
- `sanity.types.ts`, `schema.json`: TypeScript definitions file generated from sanity schemas and queries by sanity typegen https://www.sanity.io/docs/sanity-typegen#b79c963e4cf4
> feat: add rule for sanity.config.*

- update.mjs
[uv](https://github.com/astral-sh/uv/) is a new Python package and project manager
uv.lock: https://docs.astral.sh/uv/concepts/projects/#project-lockfile
uv.toml: https://docs.astral.sh/uv/configuration/files/
> feat: add rule for uv

- update.mjs
Add `ROADMAP.md` to README's nesting
Adding explicit `ROADMAP.md` to not confuse further eventual `*ROADMAP*` nesting
eg. when multiple roadmaps exists like: `ROADMAP-2024.md`, `ROADMAP-2023.md` ... etc
> feat: add ROADMAP.md to README

- update.mjs
> feat: support `*.d.ts` for `*.js`

- update.mjs
add [`react-router.config`](https://reactrouter.com/explanation/special-files#react-routerconfigts) to libraries
> feat: add `react-router.config` to libraries

- update.mjs
https://bun.sh/blog/bun-lock-text-lockfile
> feat: add `bun.lock` to the workspaces

- update.mjs
This pull request adds support for `rolldown.config.*` files.
N/A
N/A
> feat: add `rolldown.config.*` to build tools

- update.mjs
This pull request adds support for `.ls-lint.yml` files.
N/A
[ls-lint documentation](https://ls-lint.org/2.3/configuration/the-basics.html#creating-configuration)
> feat: add .ls-lint.yml to linters

- update.mjs
This PR adds CSpell support.
Refs:
- [CSpell Configuration](https://cspell.org/configuration/)
None.
None.
> feat: add `.cspell*` and `cspell*` to linters

- update.mjs
This PR adds `content.config.*` to libraries since @nuxt/content v3 introduced the new config file.
Refs: 
- [Create your First Markdown Page](https://content.nuxt.com/docs/getting-started/installation#create-your-first-markdown-page)
None.
None.
> feat: add `content.config.*` to libraries

- update.mjs
add `tsdown.config.*` to build tools
> feat: add `tsdown.config.*` to build tools

- update.mjs
http://shellcheck.net/
Shellcheck is a very common linter for bash code
N/A
> Add `.shellcheckrc` to linters

- update.mjs
- `.bazelversion` (https://bazel.build/install/bazelisk#manage-with-bazelisk) -- This file is used by bazelisk to auto-manage your bazel version
- `MODULE.bazel.lock` (https://bazel.build/external/lockfile) -- this file is similar to a pnpm/yarn/npm lockfile in that it pins the deps declared in the repo's `MODULE.bazel`.
N/A
> add `.bazelversion` and `MODULE.bazel.lock` to `BUILD.bazel`

- update.mjs
This PR adds a config for [Go Micro](https://github.com/micro/micro), which will generate `*.pb.go` and `*.pb.micro.go` based on the `*.proto` files.
> feat: add *.proto for go-micro

- package.json
- pnpm-lock.yaml
> refactor: migrate to tsdown

- README.md
- update.mjs
Supports .uid for Godot files
~
https://godotengine.org/article/uid-changes-coming-to-godot-4-4/
> feat: support Godot uid

- update.mjs
Add nesting for `.bib` file under `.tex`. `.bib` file is usually used for citing in LaTex file.
N/A.
N/A.
> feat: add `bib` file

- update.mjs
add `.oxlintrc.json` to linters
> feat: add `.oxlintrc.json` to linters

- .vscode/tasks.json
- extension/package.json
- package.json
- pnpm-lock.yaml
Drop CJS build, ESM only. Requires VSCode 1.100
See also https://bsky.app/profile/sxzz.dev/post/3looj5ai4hs25
> feat!: drop cjs build, require vscode 1.100

- README.md
- update.mjs
This is a simple update for Dart-generated files by adding *.mapper.dart to dart.
These files are generated by dart_mappable package
> feet: add *.mapper.dart files

- update.mjs
add `lefthook` to `packageJSON`
N/A
N/A
> feat: add `lefthook` to `packageJSON`

- update.mjs
See [AGENT.md](https://agent.md/)
It seems like a worthwhile way to resolve the config file mess caused by  various AI tools.
> feat: add AGENT.md to provide a unified config file for codebase

- update.mjs
See [AGENTS.md](https://agents.md/)
The previous standard has been updated, align with the new one.
> feat: align with new standard for AGENTS.md

- .github/workflows/release.yml
- .gitignore
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR implements automated publishing of the VS Code extension through CI, with simultaneous releases to:
1. Visual Studio Marketplace
2. OpenVSX registry (for open-source VS Code alternatives)
3. GitHub Release page
The implementation will:
- Add CI workflow for automated publishing
- Handle version synchronization across all platforms
- Require `VSCE_PAT` (for VS Marketplace) and `OVSX_PAT` (for OpenVSX) secrets to be configured in the repository
> ci: add release workflow for marketplace, openvsx and github

- update.mjs
Add `default.nix` and `shell.nix` under `flake.nix`, which is usually used to call those 2 files.
N/A.
N/A.
> fix: add `default.nix` and `shell.nix` under `flake.nix`

- update.mjs
Add Alejandra formatter config file. This formatter is used to format `.nix` file.
N/A.
N/A.
> feat: add alejandra formatter config file
