- update.mjs
[Rush](https://rushjs.io/)'s monorepo doesn't have package.json
> feat: add rush.json

- update.mjs
This PR adds two folding rules useful to [Nix](https://nixos.org/guides/how-nix-works.html) package manager. I hope you don't find this too niche :)
- [`default.nix`](https://nixos.org/manual/nix/stable/command-ref/nix-build.html?highlight=default.nix#description) is like `webpack.config.js` that describes how a package should build, and is used by `nix build` command by default.
[`shell.nix`](https://nixos.org/manual/nix/stable/command-ref/nix-shell.html?highlight=shell.nix#description) commonly accompanies `default.nix` and `nix shell`, the main command that consumes it, uses `default.nix` as a fallback. Thus these two files have strong relationship.
- `flake.nix` and [`flake.lock`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#lock-files) are just like …
> Add Nix files

- update.mjs
VSCode's `settings.json` supports trailing comma, adding it to make it easier to drop the config anywhere.
> Add trailing comma

- update.mjs
It improves the lint-staged config (for PR #2) because it can use the `.lintstagedrc.*` [filename syntax](https://github.com/okonet/lint-staged#configuration).
> chore: improve lint-staged config

- update.mjs
Heya Anthony! 👋 
This is a quick PR to extend the Rust config files that are listed:
- **.rustfmt.toml** – Both `rustfmt.toml` and `clippy.toml` are valid and recognized if prefixed with a `.`
- **.clippy.toml / clippy.toml** – Configuration file for [clippy](https://github.com/rust-lang/rust-clippy), the linter typically used for Rust projects
- **cross.toml** – Configuration for [cross](https://github.com/cross-rs/cross), a common cross-compilation and testing tool
Keep up the good work! 😄
> chore: extend Rust config file list

- update.mjs
[mdsvex](https://mdsvex.com) is the de-facto markdown library for Svelte, and thus very common in Svelte/Sveltekit projects.
> Add mdsvex.config.js to Svelte

- update.mjs
I've tweaked the `docker` entries to ensure we capture more variants of the `docker-compose` file and subfiles.
This way it would cover:
- `docker-compose.yml`
- `docker-compose.dev.yml`
- `docker-compose.env`
And so-on and so forth.
Happy to take on feedback if there's a better way of doing this :)
> Captured more variants of docker-compose and its sub-files

- README.md
- update.mjs
fix https://github.com/antfu/vscode-file-nesting-config/issues/70
This PR updates the rules to include `$(capture).*.tsx` inside `*.tsx` so that files like `MyFile.test.tsx` becomes child of `MyFile.tsx`
> fix: better tsx file capture

- extension/src/fetch.ts
- update.mjs
The current update of vscode has moved the experimental flag from the settings used in the script
Now:
> feat: remove experimental flag

- .github/workflows/lint.yml
- .github/workflows/update.yml
- .vscode/launch.json
- README.md
- extension/src/fetch.ts
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- I found that the original script `eslint --ext  .`  does not work
- generated code snippet is not valid jsonc (because of losing root bracket) in README.md
> chore: lint

- update.mjs
1. `'*.cs': '$(capture).*.cs'` -  nests partial classes.  If you have `Authentication.cs`, `Authentication.Login.cs` and `Authentication.Register.cs` files, then two child files get nested under `Authentication.cs`.
2. `'I*.cs': '$(capture).cs'` - nests C# implementation under its interface. If you have `IStudentService` and `StudentService`, then `StudentService` gets nested under `IStudentService`>
> C# partial class and interface/implementation nesting

- update.mjs
Add support for the new SvelteKit's routing system naming convention found in the [official documentation](https://kit.svelte.dev/docs/routing).
It will nest files like this
- `+page.svelte``
- `+page.js`
- `+page.server.js` 
- `+layout.svelte`
- `+layout.js`
- `+layout.server.js`
> feat: add support for new SvelteKit's routing system convention

- update.mjs
There seems to be a repetition of the `tsconfig.json` file when using frameworks. I have removed `...tsconfig` from the libraries array to avoid repetition because all projects already contain a `package.json` (tsconfig is already nested under it).
This seems to have occurred in the following issues: https://github.com/antfu/vscode-file-nesting-config/issues/135 and https://github.com/antfu/vscode-file-nesting-config/issues/94
> removed tsconfig from package.json

- extension/src/fetch.ts
close https://github.com/antfu/vscode-file-nesting-config/issues/138
> fix: avoid force enabling explorer fileNesting config

- update.mjs
NodeJS was supports CommonJS modules (with `require` and `module.exports`) for long time.
Now, it support also ES6 modules (with `import` and `export`, **without `babel`**). To use ES6 modules, you can set the `type: module` in your `package.json`, and/or change file extensions to `.mjs`.
Also you can do the oppsite, if you working with ES6 modules, but you need one file to be CommonJS module, you can extension it with `.cjs`.
https://nodejs.org/api/esm.html
> support .mjs and .cjs files (ES6 and commonJS)

- update.mjs
The `deno.lock` file is automatically created by deno, so it should also be included in the `denoRuntime` array.
> Adds 'deno.lock' to denoRuntime

- update.mjs
Currently both `vite.config.*` and `svelte.config.*` duplicates basically the same files. This is not desirable as it clutters the folder structure. My proposal is to simply nest the vite config under the svelte config. I'm not sure if my change will have that effect but please edit if that's the case.
> feat: nest vite config under svelte config

- update.mjs
package managers: pip, setuptools, pipenv, poetry, hatch, pdm
config files:  isort, flake8, tox.ini, .python-version
> Expand python support

- update.mjs
Fixes common extensions for `copying` (e.g. `copying.md`) not being folded under `readme`.
> fix: nest copying* under readme

- README.md
- update.mjs
Add [Fable](https://fable.io/) support (to fold in-source compiled outputs from F# source files)
Added extensions `.fs.js(x)`, `.fs.ts(x)`, `.fs.rs`, `.fs.php`, `.fs.dart` based on these facts:
- Although Fable also supports Python in addition to JS, TS, Rust, PHP and Dart, the default output extension for Python is assigned as `.py`, which makes it somewhat inappropriate to be fold [(ref)](https://github.com/fable-compiler/Fable/blob/4f1b4cd6801ebcad71f79505e902dd0a0316179a/src/Fable.Cli/Util.fs#L145-L158)
- Although Fable itself doesn't emit `.fs.jsx`/`.fs.tsx` by default, many people override the default extensions with those to work with Vite (since Vite only transpiles JSX with those extensions)
> feat: add Fable support

- update.mjs
Wen activating source maps supports for Fable, it will generate both `.fs.js` and `.fs.js.map` files.
> Add Fable generated source maps under `.fs` files

- update.mjs
Addresses https://github.com/antfu/vscode-file-nesting-config/issues/195
New code folding for `Makefile`; all files with `.mk` prefix will be impacted.
#195
> feat: Makefile file folding

- update.mjs
Added support for razor files (`*.razor`) to include its `*.razor.cs`, `*.razor.css` and `*.razor.scss` files nested as it's in Visual Studio for a long time.
No issues yet
> feat: added `*.razor` support

- update.mjs
In a Python project, the `.pylintrc` file should be under the `pyproject.toml` file.
> feat: add pylint and linters under pyprojecttoml

- update.mjs
- Add [Solid Start](https://docs.solidjs.com/solid-start/reference/entrypoints/app-config) config file to `frameworks`
- Add [SST Ion](https://ion.sst.dev/docs/#_top) config file to `libraries`
> feat: add solidJs Start framework & SST Ion lib

- update.mjs
Sentry recently released the [@sentry/nuxt module](https://nuxt.com/modules/sentry). It introduces two files, `sentry.client.config.ts` and `sentry.server.config.ts`. This PR adds the generic `sentry.*.config.*` under the services config.  
No issues opened for this.
I tried to find the most appropriate place for this and thought it would be ~libraries~ services but would be grateful to know what you think.
> feat: add `sentry.*.config.*` for Sentry's Nuxt module

- update.mjs
This PR adds [`.cursorrules`](https://docs.cursor.com/context/rules-for-ai#cursorrules) used to instruct the AI in related features in the [Cursor IDE](https://www.cursor.com) under the services config.
None at the moment.
I thought services would be appropriate to put this under.
> feat: add `.cursorrules` to services

- update.mjs
Use .ts because afaict it is a new system that only seems to use that extension. https://nuxt.com/modules/sentry
https://github.com/antfu/vscode-file-nesting-config/issues/242
> Fix double wildcard in sentry config

- update.mjs
Although we use ESLint to check for multiple wildcards, unexpected errors can still occur. To serve as a final safeguard and prevent critical issues from affecting extension users, I propose filtering out all multiple wildcards at this stage as well. Since the ESLint rule and CI are still in effect, we can still be notified of any incidents and address them promptly, but also prevent similar incidents from occurring in the future.
- [sentry.*.config.* in package.json Breaks explorer view for JS projects #242
](https://github.com/antfu/vscode-file-nesting-config/issues/242)
- [feat: add linter to guard usage](https://github.com/antfu/vscode-file-nesting-config/commit/324d02e59504a6a8ea3866fc1cf4b14f830aa34c)
- [*.knip.* causing VSCode file explorer does not display files #186 …
> feat: throw if contains multiple wildcards

- update.mjs
Adds WebAssembly text support with a capturing group for the compiled WebAssembly binary. 
This is better than if it were reversed since not all `.wasm` files have a corresponding `.wat` file, but all `.wat` files are compiled into a corresponding `.wasm` file, conventionally with the same filename and location.
> feat: add `$(capture).wasm`

- update.mjs
Cloudflare's Wrangler now [supports](https://developers.cloudflare.com/workers/wrangler/configuration/) `wrangler.json` and `wrangler.jsonc` files, other than the usual `wrangler.toml`. This PR changes the pattern for wrangler to accept any file extension.
None.
None.
> feat: add more extension support for wrangler config file

- update.mjs
- The names need to be case sensitive so the `Cargo.lock` file (uppercase C by convention) wasn't getting matched with the cargo files.
- `Cargo.Bazel.lock` is a file that may be generated as part of [bazel's `rules_rust`](https://bazelbuild.github.io/rules_rust/crate_universe.html) -- but it is inherently linked to the rust setup, hence I added it to `Cargo.toml` here rather than `BUILD.bazel`
- `insta.yaml` is a config file for insta (https://insta.rs/) a snapshot testing library for rust.
N/A
> Fix `Cargo.lock` casing, add `Cargo.bazel.lock` and `insta.yaml`

- update.mjs
`git-lfs` (https://github.com/git-lfs/git-lfs) is a tool many repos use to manage "large" files in git checkouts. It can be configured in a repo via `.git/config` or via a root `.lfsconfig` file (https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-config.adoc)
N/A
> Add `git-lfs`'s `.lfsconfig` file

- update.mjs
This PR adds [.windsurfrules](https://docs.codeium.com/windsurf/memories#windsurfrules) used to instruct the AI in related features in the [Windsurf Editor](https://codeium.com/windsurf) under the services config.
_none_
I select the `services` section according to the existing `.cursorrules`.
> feat: add .windsurfrules to services

- update.mjs
This PR solves `*.d.ts.map` files not being nested under their corresponding `*.js` file.
> Add *.d.ts.map to *.js

- update.mjs
At Visual Studio 2022, scoped CSS for `*.cshtml` is nested under it along with `*.cshtml.cs`:
However, with the current config at VS Code, only `*.cshtml.cs` is nested:
This PR aims to make it consistent with Visual Studio's nesting:
N/A
N/A
> feat: add `*.cshtml.css` under `*.cshtml`

- update.mjs
Extends the workspaces array to include `taze.config.*` files.
_none_
See: https://github.com/antfu-collective/taze/ for more information about the tool.
> feat: add taze.config.* to workspaces array
